// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mltcxqewtjirlayxreig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sdGN4cWV3dGppcmxheXhyZWlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MzQ2MzgsImV4cCI6MjA1NjUxMDYzOH0.03aL4iwLREJiZwA3SAkkUGu5UTq_DeSudhv0eDO_Lls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);